### ISSUE TITLE
ALLOWS_SAME_TYPE_AS_ROOT_COLLECT and indirect relations

### ISSUE THREAD

**Issue by VladimirKopychev-udemy** [iwoca/django-deep-collector#34]
Hi!
I noticed the wrong logic of ALLOWS_SAME_TYPE_AS_ROOT_COLLECT options.
For example we have **Users (id, name), Organization (id, name, owner)** and **Organization_has_user(id, userId, groupId, date_added)**
Given **Organization** owned by **User (1, SomeUser)**
_1 | Some_Title | 1_
And **Organization_has_user** has for example 3 rows
_1 | 1 | 1 | 2018-04-26 
2 | 2 | 1 | 2018-04-26 
3 | 3 | 1 | 2018-04-26_ 
Let's collect the data for **_User.objects.get(id=1)._** 
When we reach Organization and then Organization_has_user relations it notices relations to User object (same type as root) I see warning about the same type as root objects, and this bit of code
```
        if not self.ALLOWS_SAME_TYPE_AS_ROOT_COLLECT:
            for field in self.get_local_fields(obj):
                if isinstance(field, ForeignKey) and not field.unique and field.rel.to == type(self.root_obj):
                    setattr(obj, field.name, self.root_obj)
```
Substitutes all user relations with self.root_obj (our given user with id=1) overriding actual relations so in 

```
collector.get_json_serialized_objects()
```
We will see all Organization_has_user instances related to User(id=1) which isn't really correct.
```
{
  "model": "organizationhasuser",
  "pk": 2,
  "fields": {
     "id": 2
     "user": 1
  }
```
Is it actually a bug or an expected behaviour? 
Is it maybe worth checking not for the same type but for the same object (by pk or something else)
As a quickest solution I've just set the ALLOWS_SAME_TYPE_AS_ROOT_COLLECT to True.

**Comment by romgar** [comment]
Hey @VladimirKopychev-udemy ! Initially, I created this collector to start from a Django `User` model and get all the related data belonging to this user, which is the main reason why I introduced this `ALLOWS_SAME_TYPE_AS_ROOT_COLLECT` parameter. If, for some reason, one of the related models also points to another user, I don't want the collector to start again to collect the whole tree of data for that new user, which could lead at the end to retrieve almost all the objects from the db.

So I would say that's more an expected behaviour, and in your example, the right thing is effectively to set the `ALLOWS_SAME_TYPE_AS_ROOT_COLLECT` to `True`.
